USE [master]
GO
/****** Object:  Database [BD_COSAPI]    Script Date: 28/01/2026 17:44:51 ******/
CREATE DATABASE [BD_COSAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_COSAPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\BD_COSAPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_COSAPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\BD_COSAPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BD_COSAPI] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_COSAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BD_COSAPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_COSAPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_COSAPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_COSAPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_COSAPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_COSAPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BD_COSAPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_COSAPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_COSAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_COSAPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_COSAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_COSAPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_COSAPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_COSAPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_COSAPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BD_COSAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_COSAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_COSAPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BD_COSAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BD_COSAPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_COSAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_COSAPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BD_COSAPI] SET RECOVERY FULL 
GO
ALTER DATABASE [BD_COSAPI] SET  MULTI_USER 
GO
ALTER DATABASE [BD_COSAPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_COSAPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BD_COSAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BD_COSAPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BD_COSAPI] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BD_COSAPI', N'ON'
GO
ALTER DATABASE [BD_COSAPI] SET QUERY_STORE = OFF
GO
USE [BD_COSAPI]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [BD_COSAPI]
GO
/****** Object:  Table [dbo].[DDATA_SAP]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DDATA_SAP](
	[iMDataSap] [bigint] IDENTITY(1,1) NOT NULL,
	[iMEjecucion] [bigint] NOT NULL,
	[tOC] [varchar](50) NULL,
	[iPosicion] [int] NULL,
	[tRucProveedor] [varchar](11) NULL,
	[tCodigoProveedor] [varchar](50) NULL,
	[tRazonSocialProveedor] [varchar](max) NULL,
	[tSociedad] [varchar](250) NULL,
	[tFactura] [varchar](50) NULL,
	[fRecepcion] [date] NULL,
	[fEmision] [date] NULL,
	[tMoneda] [varchar](3) NULL,
	[nImporteTotal] [decimal](18, 3) NULL,
	[tImportePagadoFecha] [varchar](50) NULL,
	[nImportePendiente] [decimal](18, 3) NULL,
	[tCECO] [varchar](50) NULL,
 CONSTRAINT [PK_DDATA_SAP] PRIMARY KEY CLUSTERED 
(
	[iMDataSap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DDATA_SUNAT]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DDATA_SUNAT](
	[iMDataSunat] [bigint] IDENTITY(1,1) NOT NULL,
	[iMEjecucion] [bigint] NOT NULL,
	[tNumero] [varchar](50) NULL,
	[tEmisor] [varchar](max) NULL,
	[tAdquiriente] [varchar](max) NULL,
	[fEmision] [date] NULL,
	[tFormaPago] [varchar](50) NULL,
	[fDisposicion] [datetime] NULL,
	[tPlazoPendiente] [varchar](50) NULL,
	[fPlazoAcordado] [date] NULL,
	[nMontoPendiente] [decimal](18, 3) NULL,
	[tMoneda] [varchar](3) NULL,
	[nImporteTotal] [decimal](18, 3) NULL,
	[tMarca] [varchar](50) NULL,
	[tCondicion] [varchar](50) NULL,
	[tEstado] [varchar](50) NULL,
	[iInconsistencias] [int] NULL,
 CONSTRAINT [PK_DDATA_SUNAT] PRIMARY KEY CLUSTERED 
(
	[iMDataSunat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEJECUCION]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEJECUCION](
	[iMEjecucion] [bigint] IDENTITY(1,1) NOT NULL,
	[tTipo] [varchar](1) NULL,
	[iMSAP] [int] NOT NULL,
	[tRuc] [varchar](11) NOT NULL,
	[fDisposicion] [date] NULL,
	[fEmisionDesde] [date] NULL,
	[fEmisionHasta] [date] NULL,
	[tVersionGemini] [varchar](50) NULL,
	[iUsuarioEjecucion] [bigint] NULL,
	[fRegistro] [datetime] NULL,
 CONSTRAINT [PK_DEJECUCION] PRIMARY KEY CLUSTERED 
(
	[iMEjecucion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEJECUCION_LISTA_BLANCA]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEJECUCION_LISTA_BLANCA](
	[iMDetalle] [bigint] IDENTITY(1,1) NOT NULL,
	[iMEjecucion] [bigint] NOT NULL,
	[tRucListaBlanca] [varchar](11) NOT NULL,
 CONSTRAINT [PK_DEJECUCION_LISTA_BLANCA] PRIMARY KEY CLUSTERED 
(
	[iMDetalle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DSEGUIMIENTO]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DSEGUIMIENTO](
	[iMSeguimiento] [bigint] IDENTITY(1,1) NOT NULL,
	[iMEjecucion] [bigint] NOT NULL,
	[iMEvento] [int] NULL,
	[fRegistro] [datetime] NULL,
	[tDescripcion] [varchar](250) NULL,
 CONSTRAINT [PK_DSEGUIMIENTO] PRIMARY KEY CLUSTERED 
(
	[iMSeguimiento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MCLASE_DOCUMENTO_COMPRA]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MCLASE_DOCUMENTO_COMPRA](
	[tClase] [varchar](5) NULL,
	[tDenominacion] [varchar](50) NULL,
	[iRangoDesde] [bigint] NULL,
	[iRangoHasta] [bigint] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MCONSUMO_GEMINI]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MCONSUMO_GEMINI](
	[iMConsumo] [bigint] IDENTITY(1,1) NOT NULL,
	[iMEjecucion] [bigint] NOT NULL,
	[iTransacciones] [int] NULL,
	[iTokenIn] [bigint] NULL,
	[ITokenOut] [bigint] NULL,
 CONSTRAINT [PK_MCONSUMO_GEMINI] PRIMARY KEY CLUSTERED 
(
	[iMConsumo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MDESCARGA]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MDESCARGA](
	[iMDescarga] [bigint] IDENTITY(1,1) NOT NULL,
	[iMEjecucion] [bigint] NULL,
	[iMDataSap] [bigint] NULL,
	[tOriigen] [varchar](5) NULL,
	[tRutaArchivo] [varchar](max) NULL,
	[tExrension] [varchar](5) NULL,
	[tArchivo] [varchar](100) NULL,
	[tPesokb] [int] NULL,
 CONSTRAINT [PK_MDESCARGA] PRIMARY KEY CLUSTERED 
(
	[iMDescarga] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEVENTO]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEVENTO](
	[iMEvento] [int] IDENTITY(1,1) NOT NULL,
	[tEvento] [varchar](50) NULL,
 CONSTRAINT [PK_MEVENTO] PRIMARY KEY CLUSTERED 
(
	[iMEvento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MLISTA_BLANCA]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MLISTA_BLANCA](
	[tRucListaBlanca] [varchar](11) NOT NULL,
	[tRazonSocial] [varchar](max) NULL,
	[lActivo] [bit] NULL,
	[iUsuarioModificacion] [bigint] NULL,
	[fRegistro] [datetime] NULL,
	[iUsuarioRegistro] [bigint] NULL,
	[fModificacion] [datetime] NULL,
 CONSTRAINT [PK_MLISTA_BLANCA] PRIMARY KEY CLUSTERED 
(
	[tRucListaBlanca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MROL]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MROL](
	[iMRol] [int] IDENTITY(1,1) NOT NULL,
	[tRol] [varchar](50) NULL,
	[lActivo] [bit] NULL,
 CONSTRAINT [PK_MROL] PRIMARY KEY CLUSTERED 
(
	[iMRol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MSAP]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MSAP](
	[iMSAP] [int] IDENTITY(1,1) NOT NULL,
	[tUsuario] [varchar](100) NULL,
	[tClave] [nvarchar](50) NULL,
	[iUsuarioModificacion] [bigint] NULL,
	[fRegistro] [datetime] NULL,
	[iUsuarioRegistro] [bigint] NULL,
	[fModificacion] [datetime] NULL,
	[lActivo] [bit] NULL,
 CONSTRAINT [PK_MSAP] PRIMARY KEY CLUSTERED 
(
	[iMSAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MSAP_SOCIEDAD]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MSAP_SOCIEDAD](
	[iMDetalle] [bigint] IDENTITY(1,1) NOT NULL,
	[iMSAP] [int] NOT NULL,
	[tRuc] [varchar](11) NOT NULL,
	[lActivo] [bit] NULL,
	[fRegistro] [datetime] NULL,
	[iUsuarioRegistro] [bigint] NULL,
	[fModificacion] [datetime] NULL,
	[iUsuarioModificacion] [bigint] NULL,
 CONSTRAINT [PK_MSAP_SOCIEDAD] PRIMARY KEY CLUSTERED 
(
	[iMDetalle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MSOCIEDAD]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MSOCIEDAD](
	[tRuc] [varchar](11) NOT NULL,
	[tRazonSocial] [nchar](10) NULL,
	[tUsuario] [varchar](50) NULL,
	[tClave] [nvarchar](max) NULL,
	[iUsuarioBaja] [bigint] NULL,
	[fRegistro] [datetime] NULL,
	[iUsuarioRegistro] [bigint] NULL,
	[fModificacion] [datetime] NULL,
	[iUsuarioModificacion] [bigint] NULL,
	[fBaja] [datetime] NULL,
	[lActivo] [bit] NULL,
 CONSTRAINT [PK_MSOCIEDAD] PRIMARY KEY CLUSTERED 
(
	[tRuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MUSUARIO]    Script Date: 28/01/2026 17:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MUSUARIO](
	[iMusuario] [bigint] IDENTITY(1,1) NOT NULL,
	[tCorreo] [varchar](250) NULL,
	[tClave] [nvarchar](max) NULL,
	[tNombre] [varchar](250) NULL,
	[tApellidos] [varchar](250) NULL,
	[iMRol] [int] NULL,
	[lNotificacion] [bit] NULL,
	[fRegistro] [datetime] NULL,
	[iUsuarioRegistro] [bigint] NULL,
	[fModificacion] [datetime] NULL,
	[iUsuarioModificacion] [bigint] NULL,
	[fBaja] [datetime] NULL,
	[iUsuarioBaja] [bigint] NULL,
	[lActivo] [bit] NULL,
 CONSTRAINT [PK_MUSUARIO] PRIMARY KEY CLUSTERED 
(
	[iMusuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEJECUCION] ADD  CONSTRAINT [DF_DEJECUCION_fRegistro]  DEFAULT (getdate()) FOR [fRegistro]
GO
ALTER TABLE [dbo].[DSEGUIMIENTO] ADD  CONSTRAINT [DF_DSEGUIMIENTO_fRegistro]  DEFAULT (getdate()) FOR [fRegistro]
GO
ALTER TABLE [dbo].[MLISTA_BLANCA] ADD  CONSTRAINT [DF_MLISTA_BLANCA_lActivo]  DEFAULT ((1)) FOR [lActivo]
GO
ALTER TABLE [dbo].[MLISTA_BLANCA] ADD  CONSTRAINT [DF_MLISTA_BLANCA_fRegistro]  DEFAULT (getdate()) FOR [fRegistro]
GO
ALTER TABLE [dbo].[MROL] ADD  CONSTRAINT [DF_MROL_lActivo]  DEFAULT ((1)) FOR [lActivo]
GO
ALTER TABLE [dbo].[MSAP] ADD  CONSTRAINT [DF_MSAP_fRegistro]  DEFAULT (getdate()) FOR [fRegistro]
GO
ALTER TABLE [dbo].[MSAP] ADD  CONSTRAINT [DF_MSAP_lActivo]  DEFAULT ((1)) FOR [lActivo]
GO
ALTER TABLE [dbo].[MSAP_SOCIEDAD] ADD  CONSTRAINT [DF_MSAP_SOCIEDAD_lActivo]  DEFAULT ((1)) FOR [lActivo]
GO
ALTER TABLE [dbo].[MSOCIEDAD] ADD  CONSTRAINT [DF_MSOCIEDAD_fRegistro]  DEFAULT (getdate()) FOR [fRegistro]
GO
ALTER TABLE [dbo].[MSOCIEDAD] ADD  CONSTRAINT [DF_MSOCIEDAD_lActivo]  DEFAULT ((1)) FOR [lActivo]
GO
ALTER TABLE [dbo].[MUSUARIO] ADD  CONSTRAINT [DF_MUSUARIO_fRegistro]  DEFAULT (getdate()) FOR [fRegistro]
GO
ALTER TABLE [dbo].[MUSUARIO] ADD  CONSTRAINT [DF_MUSUARIO_lActivo]  DEFAULT ((1)) FOR [lActivo]
GO
ALTER TABLE [dbo].[DDATA_SAP]  WITH CHECK ADD  CONSTRAINT [FK_DDATA_SAP_DEJECUCION] FOREIGN KEY([iMEjecucion])
REFERENCES [dbo].[DEJECUCION] ([iMEjecucion])
GO
ALTER TABLE [dbo].[DDATA_SAP] CHECK CONSTRAINT [FK_DDATA_SAP_DEJECUCION]
GO
ALTER TABLE [dbo].[DDATA_SUNAT]  WITH CHECK ADD  CONSTRAINT [FK_DDATA_SUNAT_DEJECUCION] FOREIGN KEY([iMEjecucion])
REFERENCES [dbo].[DEJECUCION] ([iMEjecucion])
GO
ALTER TABLE [dbo].[DDATA_SUNAT] CHECK CONSTRAINT [FK_DDATA_SUNAT_DEJECUCION]
GO
ALTER TABLE [dbo].[DEJECUCION]  WITH CHECK ADD  CONSTRAINT [FK_DEJECUCION_MSAP] FOREIGN KEY([iMSAP])
REFERENCES [dbo].[MSAP] ([iMSAP])
GO
ALTER TABLE [dbo].[DEJECUCION] CHECK CONSTRAINT [FK_DEJECUCION_MSAP]
GO
ALTER TABLE [dbo].[DEJECUCION]  WITH CHECK ADD  CONSTRAINT [FK_DEJECUCION_MSOCIEDAD] FOREIGN KEY([tRuc])
REFERENCES [dbo].[MSOCIEDAD] ([tRuc])
GO
ALTER TABLE [dbo].[DEJECUCION] CHECK CONSTRAINT [FK_DEJECUCION_MSOCIEDAD]
GO
ALTER TABLE [dbo].[DEJECUCION]  WITH CHECK ADD  CONSTRAINT [FK_DEJECUCION_MUSUARIO] FOREIGN KEY([iUsuarioEjecucion])
REFERENCES [dbo].[MUSUARIO] ([iMusuario])
GO
ALTER TABLE [dbo].[DEJECUCION] CHECK CONSTRAINT [FK_DEJECUCION_MUSUARIO]
GO
ALTER TABLE [dbo].[DEJECUCION_LISTA_BLANCA]  WITH CHECK ADD  CONSTRAINT [FK_DEJECUCION_LISTA_BLANCA_DEJECUCION] FOREIGN KEY([iMEjecucion])
REFERENCES [dbo].[DEJECUCION] ([iMEjecucion])
GO
ALTER TABLE [dbo].[DEJECUCION_LISTA_BLANCA] CHECK CONSTRAINT [FK_DEJECUCION_LISTA_BLANCA_DEJECUCION]
GO
ALTER TABLE [dbo].[DEJECUCION_LISTA_BLANCA]  WITH CHECK ADD  CONSTRAINT [FK_DEJECUCION_LISTA_BLANCA_MLISTA_BLANCA] FOREIGN KEY([tRucListaBlanca])
REFERENCES [dbo].[MLISTA_BLANCA] ([tRucListaBlanca])
GO
ALTER TABLE [dbo].[DEJECUCION_LISTA_BLANCA] CHECK CONSTRAINT [FK_DEJECUCION_LISTA_BLANCA_MLISTA_BLANCA]
GO
ALTER TABLE [dbo].[DSEGUIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_DSEGUIMIENTO_DEJECUCION] FOREIGN KEY([iMEjecucion])
REFERENCES [dbo].[DEJECUCION] ([iMEjecucion])
GO
ALTER TABLE [dbo].[DSEGUIMIENTO] CHECK CONSTRAINT [FK_DSEGUIMIENTO_DEJECUCION]
GO
ALTER TABLE [dbo].[DSEGUIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_DSEGUIMIENTO_MEVENTO] FOREIGN KEY([iMEvento])
REFERENCES [dbo].[MEVENTO] ([iMEvento])
GO
ALTER TABLE [dbo].[DSEGUIMIENTO] CHECK CONSTRAINT [FK_DSEGUIMIENTO_MEVENTO]
GO
ALTER TABLE [dbo].[MCONSUMO_GEMINI]  WITH CHECK ADD  CONSTRAINT [FK_MCONSUMO_GEMINI_DEJECUCION] FOREIGN KEY([iMEjecucion])
REFERENCES [dbo].[DEJECUCION] ([iMEjecucion])
GO
ALTER TABLE [dbo].[MCONSUMO_GEMINI] CHECK CONSTRAINT [FK_MCONSUMO_GEMINI_DEJECUCION]
GO
ALTER TABLE [dbo].[MDESCARGA]  WITH CHECK ADD  CONSTRAINT [FK_MDESCARGA_DDATA_SAP] FOREIGN KEY([iMDataSap])
REFERENCES [dbo].[DDATA_SAP] ([iMDataSap])
GO
ALTER TABLE [dbo].[MDESCARGA] CHECK CONSTRAINT [FK_MDESCARGA_DDATA_SAP]
GO
ALTER TABLE [dbo].[MDESCARGA]  WITH CHECK ADD  CONSTRAINT [FK_MDESCARGA_DEJECUCION] FOREIGN KEY([iMEjecucion])
REFERENCES [dbo].[DEJECUCION] ([iMEjecucion])
GO
ALTER TABLE [dbo].[MDESCARGA] CHECK CONSTRAINT [FK_MDESCARGA_DEJECUCION]
GO
ALTER TABLE [dbo].[MSAP_SOCIEDAD]  WITH CHECK ADD  CONSTRAINT [FK_MSAP_SOCIEDAD_MSAP] FOREIGN KEY([iMSAP])
REFERENCES [dbo].[MSAP] ([iMSAP])
GO
ALTER TABLE [dbo].[MSAP_SOCIEDAD] CHECK CONSTRAINT [FK_MSAP_SOCIEDAD_MSAP]
GO
ALTER TABLE [dbo].[MSAP_SOCIEDAD]  WITH CHECK ADD  CONSTRAINT [FK_MSAP_SOCIEDAD_MSOCIEDAD] FOREIGN KEY([tRuc])
REFERENCES [dbo].[MSOCIEDAD] ([tRuc])
GO
ALTER TABLE [dbo].[MSAP_SOCIEDAD] CHECK CONSTRAINT [FK_MSAP_SOCIEDAD_MSOCIEDAD]
GO
ALTER TABLE [dbo].[MUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK_MUSUARIO_MROL] FOREIGN KEY([iMRol])
REFERENCES [dbo].[MROL] ([iMRol])
GO
ALTER TABLE [dbo].[MUSUARIO] CHECK CONSTRAINT [FK_MUSUARIO_MROL]
GO
USE [master]
GO
ALTER DATABASE [BD_COSAPI] SET  READ_WRITE 
GO
